include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_declarations: error
    prefer_const_constructors: error

linter:
  rules:
    prefer_const_declarations: false
    prefer_const_constructors: false
