// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH_kQHWp3j_hKt41v4ya5rNCuDI5Iekxk',
    appId: '1:999447001138:web:82afdb443c1caffc78242b',
    messagingSenderId: '999447001138',
    projectId: 'chatapp-1d4ff',
    authDomain: 'chatapp-1d4ff.firebaseapp.com',
    storageBucket: 'chatapp-1d4ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9LMQ_CYZ59L1_mkBrqQ_VTTAKLACTXQI',
    appId: '1:999447001138:android:2516701f9754e38078242b',
    messagingSenderId: '999447001138',
    projectId: 'chatapp-1d4ff',
    storageBucket: 'chatapp-1d4ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzP5FHsRZDBQ7_7yG8I3L-lS2NbApqn2I',
    appId: '1:999447001138:ios:d2e0d0abc71d627d78242b',
    messagingSenderId: '999447001138',
    projectId: 'chatapp-1d4ff',
    storageBucket: 'chatapp-1d4ff.appspot.com',
    iosClientId: '999447001138-g3suseq4rletsn7tpl00c44gbk1of17h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestChatapp',
  );
}
